**Matrix Operations in Python**

Run each of the code cells in sequence by clicking the (>) button or hitting shift-enter.

First we need to import some stuff from the numpy package to do matrix operations in python.

In [3]:
from numpy import array, matmul
from numpy.linalg import inv, det, solve

Define a matrix as an array of row vectors:

In [ ]:
M = array([[1,2,3],[4,5,6],[7,8,9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


The safest way to make vectors is to define as nx1 or 1xn matrices. Note that in this case, x is the dot product of a and b

In [4]:
a = array([[1,2,3]])
b = array([[4],[5],[6]])
c = matmul(a,b)
print('a =', a)
print('b =', b)
print('ab =', c)

a = [[1 2 3]]
b = [[4]
 [5]
 [6]]
ab = [[32]]


We can also do it this way using transpose

In [8]:
a = array([[1,2,3]])
b = array([[4,5,6]])
c = matmul(a,b.T)
print('a =', a)
print('b =', b)
print('a•b =', c)

a = [[1 2 3]]
b = [[4 5 6]]
a•b = [[32]]


### Part I: 

Define the following matrices in Python:

$
A=\begin{bmatrix} 1 & 0 &  2 \\ 3 & -1 & 0  \\ 0&5&1 \end{bmatrix}
$



$
B=\begin{bmatrix} 1&1&0 \\ 0&2&1 \\ 3&-1&0 \end{bmatrix}
$

In [ ]:
A =
B =

You can do arithmatic with matrices in python.

Addition and subtraction is just like numbers using + and -

multiply using matmul(A,B). Note that A*B gives something different!

Compute the following:

A+B

AB

BA

A + B

$A^2$



In [ ]:
#  A + B


In [ ]:
# AB


In [ ]:
# BA


In [ ]:
# A^2


You can also do more complex operations like determinant, transpose, and inverse. Row Reduction is a symbolic operation, not numerical, so we will skip this for now.

For a matrix M:

Transpose: M.T

Inverse: inv(M)

Determinat: det(M)

Compute the following:


In [ ]:
# Transpose of A


In [ ]:
# Inverse of A


In [ ]:
# det(A)


In [ ]:
# det(B)


In [ ]:
# det(AB)


In [ ]:
# det (A+B)

Is det(AB)=det(A)det(B)?

Is det(A + B)= det(A) + det(B)?

### Part 2

Finally, we can solve systems of equations using these tools. python also has a handy function solve. Type help(solve) to see how this works.

Solve the following systems of equations using the matrix inverse and the solve function.

<br><br>
1)
$
\begin{array}{rcrcrcr}
x   &-& 2y& & &=&4\\
5x && &+&2z&=&7\\
x &+&2y&-&z&=&3
\end{array}
$
<br><br>
2)
$
\begin{array}{rcrcrcr}
4x   &+& 6y&-&12z &=&7\\
5x &-&2y &+&4z&=&-15\\
3x &+&4y&-&8z&=&4
\end{array}
$

In [ ]:
help(solve)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.

    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.

    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.

    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is (..., M) if b is
        shape (M,) and (..., M, K) if b is (..., M, K), where the "..." part is
        broadcasted between a and b.

    Raises
    ------
    LinAlgError
        If `a` is singular or not square.

    See Also
    --------
    scipy.linalg.solve : Similar function in SciPy.

    Notes
    -----
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.

    The solutions are computed us

In [ ]:
# Solve (1)  here


In [ ]:
# Solve (2)  here
