**Matrix Operations in Python**

Run each of the code cells in sequence by clicking the (>) button or hitting shift-enter.

First we need to import some stuff from the numpy package to do matrix operations in python.

In [ ]:
from numpy import array, matmul
from numpy.linalg import inv, det, solve

Define a matrix as an array of row vectors:

In [ ]:
M = array([[1,2,3],[4,5,6],[7,8,9]])
print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Part I: Define the following matrices in Python:

$
A=\begin{bmatrix} 1 & 0 &  2 \\ 3 & -1 & 0  \\ 0&5&1 \end{bmatrix}
$



$
B=\begin{bmatrix} 1&1&0 \\ 0&2&1 \\ 3&-1&0 \end{bmatrix}
$

In [ ]:
A =
B =

You can do arithmatic with matrices in python.

Addition and subtraction is just like numbers using + and -

multiply using matmul(A,B). Note that A*B gives something different!

Compute the following:

A+B

AB

BA

A + B

$A^2$



In [ ]:
#  A + B


In [ ]:
# AB


In [ ]:
# BA


In [ ]:
# A^2


You can also do more complex operations like determinant, transpose, and inverse. Row Reduction is a symbolic operation, not numerical, so we will skip this for now.

For a matrix M:

Transpose: M.T

Inverse: inv(M)

Determinat: det(M)

Compute the following:


In [ ]:
# Transpose of A


In [ ]:
# Inverse of A


In [ ]:
# det(A)


In [ ]:
# det(B)


In [ ]:
# det(AB)


In [ ]:
# det (A+B)

Is det(AB)=det(A)det(B)?

Is det(A + B)= det(A) + det(B)?

Finally, we can solve systems of equations using these tools. python also has a handy function solve. Type help(solve) to see how this works.

Solve the following systems of equations using the matrix inverse and the solve function.

<br><br>
1)
$
\begin{array}{rcrcrcr}
x   &-& 2y& & &=&4\\
5x && &+&2z&=&7\\
x &+&2y&-&z&=&3
\end{array}
$
<br><br>
2)
$
\begin{array}{rcrcrcr}
4x   &+& 6y&-&12z &=&7\\
5x &-&2y &+&4z&=&-15\\
3x &+&4y&-&8z&=&4
\end{array}
$

In [ ]:
# Solve (1)  here


In [ ]:
# Solve (2)  here
