In [22]:
from numpy.linalg import eig, inv, det
from numpy import shape, array, matmul, dot

Define a matrix and find its eigenvectors and eigenvalues

In [3]:
A = array([[0, 2],[ 1, -1]])
w, U = eig(A)

print("Eigen values w=",w)
print("Eigen vectors:")
print("u1 = ", U[:,0])
print("u2 = ", U[:,1])

Eigen values w= [ 1. -2.]
Eigen vectors:
u1 =  [0.89442719 0.4472136 ]
u2 =  [-0.70710678  0.70710678]


In [4]:
print(U)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [23]:
dot(U[:,0],U[:,1])

-0.31622776601683783

Try some matrix products and see if it's what you expected to find.

a) Make a single column vector $\vec{u}$ from the first column of U, which would be the 1st eigenvector, and compute $A\vec{u}$. Do you get $λ\vec{u}$?

b)  AU

c) compute $U^{-1}AU$ what do you get?

In [18]:
u = U[:,0] # First column is first eigenvector
#ans = matmul()
#print(ans)

AU = matmul(A,U)
UAU = matmul(inv(U),AU)
print('inv(U)AU = \n', UAU)

inv(U)AU = 
 [[ 1.00000000e+00  5.37218376e-16]
 [-1.46547895e-18 -2.00000000e+00]]


In [ ]:
#z = 1j
print(z**2)

(-1+0j)


In [13]:
A = array([[0, 2],[ 1, -1]])
u1 =  array([0.89442719, 0.4472136 ])
print(u1)
print(matmul(A,u1))

[0.89442719 0.4472136 ]
[0.8944272  0.44721359]


In [15]:
u1 =  array([[0.89442719], [0.4472136 ]])
print(u1)
print(matmul(A,u1))

[[0.89442719]
 [0.4472136 ]]
[[0.8944272 ]
 [0.44721359]]


In [16]:
u1 =  array([[0.89442719, 0.4472136 ]])
print(u1)
print(matmul(A,u1))

[[0.89442719 0.4472136 ]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)