Run each of the code cells in sequence by clicking the (>) button or hitting shift-enter. 

First we need to import some stuff from the numpy package to do matrix operations in python.

In [3]:
from numpy import array, matmul
from numpy.linalg import inv, det, solve

Define some matrices as an arrays of row vectors:

In [4]:
M = array([[1,2,3],[4,5,6],[7,8,9]])
I=array([[1, 0 ],[0, 1]])
A=array([[0,1 ],[1,0]])
B=array([[0,-1 ],[-1,0]])
C=array([[-1, 0 ],[0, -1]])
print(I)
print(A)
print(B)
print(C)

[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
[[ 0 -1]
 [-1  0]]
[[-1  0]
 [ 0 -1]]


Use matmul(A,B) to create a multiplication table for this set of matrices. Is this set a group? Is it isomorphic to a known group?

In [5]:
print(matmul(A,B))

[[-1  0]
 [ 0 -1]]
